# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

varInfInputC <- function(model_r, print, printMod, stepType, maxTotalIter, maxEIter, maxAlphaIter, maxThetaIter, maxLSIter, elboTol, alphaTol, thetaTol, aNaught, tau, bMax, bNaught, bMult, vCutoff, holdConstSEXP) {
    .Call('mixedMem_varInfInputC', PACKAGE = 'mixedMem', model_r, print, printMod, stepType, maxTotalIter, maxEIter, maxAlphaIter, maxThetaIter, maxLSIter, elboTol, alphaTol, thetaTol, aNaught, tau, bMax, bNaught, bMult, vCutoff, holdConstSEXP)
}

computeElboC <- function(model_r) {
    .Call('mixedMem_computeElboC', PACKAGE = 'mixedMem', model_r)
}

varInfInputExtC <- function(model_r, print, printMod, stepType, maxTotalIter, maxEIter, maxAlphaIter, maxThetaIter, maxLSIter, elboTol, alphaTol, thetaTol, aNaught, tau, bMax, bNaught, bMult, vCutoff, holdConstSEXP) {
    .Call('mixedMem_varInfInputExtC', PACKAGE = 'mixedMem', model_r, print, printMod, stepType, maxTotalIter, maxEIter, maxAlphaIter, maxThetaIter, maxLSIter, elboTol, alphaTol, thetaTol, aNaught, tau, bMax, bNaught, bMult, vCutoff, holdConstSEXP)
}

computeElboExtC <- function(model_r) {
    .Call('mixedMem_computeElboExtC', PACKAGE = 'mixedMem', model_r)
}

rDirichlet_sw <- function(alpha_r) {
    .Call('mixedMem_rDirichlet_sw', PACKAGE = 'mixedMem', alpha_r)
}

rsampler_sw <- function(prob_r, sample_r) {
    .Call('mixedMem_rsampler_sw', PACKAGE = 'mixedMem', prob_r, sample_r)
}

