# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

varInfInputC <- function(model_r, print, printMod, stepType, maxTotalIter, maxEIter, maxAlphaIter, maxThetaIter, maxLSIter, elboTol, alphaTol, thetaTol, aNaught, tau, bMax, bNaught, bMult, vCutoff, holdConstSEXP) {
    .Call('mixedMem_varInfInputC', PACKAGE = 'mixedMem', model_r, print, printMod, stepType, maxTotalIter, maxEIter, maxAlphaIter, maxThetaIter, maxLSIter, elboTol, alphaTol, thetaTol, aNaught, tau, bMax, bNaught, bMult, vCutoff, holdConstSEXP)
}

computeElboInputC <- function(model_r) {
    .Call('mixedMem_computeElboInputC', PACKAGE = 'mixedMem', model_r)
}

mcmcInputC <- function(model_r, burnIn, samples, thin, print, fileNames, newFiles, omega, eta, whichWrite) {
    invisible(.Call('mixedMem_mcmcInputC', PACKAGE = 'mixedMem', model_r, burnIn, samples, thin, print, fileNames, newFiles, omega, eta, whichWrite))
}

