# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

varInfInputC <- function(model_r) {
    .Call('mixedMem_varInfInputC', PACKAGE = 'mixedMem', model_r)
}

computeElboC <- function(model_r) {
    .Call('mixedMem_computeElboC', PACKAGE = 'mixedMem', model_r)
}

heldOutInputC <- function(model_r) {
    .Call('mixedMem_heldOutInputC', PACKAGE = 'mixedMem', model_r)
}

